### ISSUE TITLE
http://curl.haxx.se/ca/cacert.pem instead of HTTPS

### ISSUE THREAD

**Issue by samwalshnz** [TeamOffshoot/http#1]
If there a reason why the composer.json file is configured to download the `pem` file via http instead of https?
```
"dist": {
  "url": "http://curl.haxx.se/ca/cacert.pem",
  "type": "file"
}
```

**Comment by samwalshnz** [comment]
https://getcomposer.org/doc/06-config.md#secure-http

**Comment by neilhamilton** [comment]
Hi there, we are archiving this repo since it is no longer used and we will no longer be maintaining it. Please use something like [Guzzle](https://github.com/guzzle/guzzle) instead.
